// Geometric Figures  Copyright (C) 2015--2016  Lukáš Ondráček <ondracek.lukas@gmail.com>, see README file

// scriptWrappers module is generated by scriptWrappers.pl
// This file exists to correct Makefile dependencies.

#include <Python.h>
#include "scriptWrappers.c.tmp"
